version: "3"

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    volumes: 
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: example
      POSTGRES_DB: example
      POSTGRES_PASSWORD: example

  app:
    image: node:14-alpine
    working_dir: /app
    ports: 
        - 3000:3000
    volumes: 
      - ./src:/app
    depends_on: 
      - postgres
    command: node app.js

volumes: 
  postgres: {}